name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  Apply-Terraform-to-Production:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.TF_VAR_do_token }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      TF_VAR_pvt_key: ${{ secrets.TF_VAR_pvt_key }}
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
 
      - name: Terraform Init
        run: terraform init

      - name: Check Terraform fmt
        run: terraform fmt -check

      - name: Validate Configuration
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_INPUT: false
